services:
  av-service:
    image: ghcr.io/cipfz/youtobe-parser:latest
    pull_policy: always
    container_name: av-service
    
    # 直接指定容器运行时的 UID/GID，确保生成的文件不属于 root
    user: "${UID}:${GID}"
    
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./models/whisper:/models/whisper
      - ./logs:/app/logs
    environment:
      - AV_TASK_DB_PATH=/data/output/task_manager.db
      - LD_LIBRARY_PATH=/usr/local/lib